language: node_js
node_js:
  - 10
before_script:
  - npm install @neuralegion/nexploit-cli -g || true
script:
  - printf "Retest a scan"
  - >
    NEW_SCAN_ID=$(nexploit-cli scan:retest
    --token=$NEXPLOIT_TOKEN 
    $OLD_SCAN_ID)
  - printf "Scan was started with ID https://nexploit.app/scans/$NEW_SCAN_ID\n"
  - printf "Wait for issues ⏳\n"
  - >
    (nexploit-cli scan:polling
    --interval 30s
    --timeout 20m
    --token $NEXPLOIT_TOKEN
    --breakpoint medium_issue $NEW_SCAN_ID)
allow_failure: true
after_script:
  - printf "Stop Scan 🛑" 
  - nexploit-cli scan:stop --token $NEXPLOIT_TOKEN $NEW_SCAN_ID

