version:'3'
services:
 brokencrystals.local:
  image: neuralegion/brokencrystals
 repeater:
  image: neuralegion/repeater:latest
  restart: always
  environment:
   REPEATER_TOKEN: ${NEURALEGION_TOKEN}
   REPEATER_AGENT: ${REPEATER}
   DEBUG: nexploit-cli
